apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
    env: learning
  annotations:
    metallb.universe.tf/allow-shared-ip: "ft_services"
spec:
  type: LoadBalancer
  ports:
    - name: ftp
      port: 21
      targetPort: 21
    - name: ftp-data
      port: 20
      targetPort: 20
  selector:
    app: ftps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ftps
    env: learning
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
        env: learning
    spec:
      # volumes:
      #   - name: ftps-config
      #     configMap:
      #         name: ftps-config
      containers:
      - name: ftps
        image: my-ftps
        imagePullPolicy: Never
        env:
        - name: USER
          value: 'ftps'
        - name: PASSWORD
          value: 'ftps'
        ports:
        - containerPort: 21
          name : ftp
        - containerPort: 20
          name : ftp-data
