apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
    env: learning
  annotations:
    metallb.universe.tf/allow-shared-ip: "ft_services"
spec:
  type: LoadBalancer
  ports:
    - name: ftp
      port: 21
      targetPort: 21
    - name: ftp-data
      port: 20
      targetPort: 20
    - name: implicit-ftp-over-tls
      port: 990
      targetPort: 990
    - port: 20000
      targetPort: 20000
      name: pasv-0
    - port: 20001
      name: pasv-1
      targetPort: 20001
    - port: 20002
      name: pasv-2
      targetPort: 20002
  selector:
    app: ftps
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pv-claim
  labels:
    app: ftps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ftps
    env: learning
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
        env: learning
    spec:
      terminationGracePeriodSeconds: 3  
      volumes:
        - name: vsftpd-config
          configMap:
              name: vsftpd-config
        - name: ftps-persistent-storage
          persistentVolumeClaim:
            claimName: ftps-pv-claim
      containers:
      - name: ftps
        image: my-ftps
        imagePullPolicy: Never
        args: ['vsftpd', '/custom_config/vsftpd.conf']
        env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: ftps-secrets
              key: USER
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: ftps-secrets
              key: PASSWORD
        ports:
        - containerPort: 21
          name : ftp
        - containerPort: 20
          name : ftp-data
        - containerPort: 990
          name : implicit-tls
        - containerPort: 20000
        - containerPort: 20001
        - containerPort: 20002
        volumeMounts:
          - name: ftps-persistent-storage
            mountPath: /ftps_data
          - name: vsftpd-config
            mountPath: /custom_config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vsftpd-config
  labels:
    app: nginx
    env: learning 
data:
  vsftpd.conf: |
    # vsftpd.conf may be used to control various aspects of vsftpd's behaviour.
    # By default, vsftpd looks for this file at the location /etc/vsftpd.conf

    ftpd_banner=Hola ! ur connected to my ftps server. Give me 100.

    # ftp over ssl stuff
    ssl_enable=YES
    ssl_ciphers=HIGH
    anonymous_enable=YES
    allow_anon_ssl=NO
    rsa_cert_file=/etc/ssl/private/vsftpd.pem
    rsa_private_key_file=/etc/ssl/private/vsftpd.pem

    # fix 500 server error  child died
    seccomp_sandbox=NO

    # allow local users
    local_enable=YES
    # Uncomment this to enable any form of FTP write command.
    write_enable=YES

    # debug_ssl=YES
    # xferlog_std_format=YES
    # log_ftp_protocol=YES
    # xferlog_file=/var/log/xfer.log
    # vsftpd_log_file=/var/log/vsftpd/vsftpd.log

    xferlog_enable=YES
    vsftpd_log_file=/var/log/vsftpd/vsftpd.log

    # restrict path
    allow_writeable_chroot=YES
    chroot_local_user=YES
    local_root=/ftps_data/


    pasv_enable=YES
    pasv_min_port=20000
    pasv_max_port=20002
    pasv_address=172.20.0.10
  