apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
    env: learning
spec:
  type: ClusterIP
  ports:
    - port: 8086
      targetPort: 8086
  selector:
    app: influxdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  labels:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: influxdb
    env: learning
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
        env: learning
    spec:
      volumes:
        - name: influxdb-persistent-storage
          persistentVolumeClaim:
            claimName: influxdb-pv-claim
      containers:
      - name: influxdb
        image: my-influxdb
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
          name: http
        env:
          - name: INFLUXDB_DB
            value: 'grafana'
          - name: INFLUXDB_ADMIN_USER
            value: 'groot'
          - name: INFLUXDB_ADMIN_PASSWORD
            value: 'icantstopthisfeelingdeepinsideofme'
          - name: INFLUXDB_USER
            value: 'grafana'
          - name: INFLUXDB_USER_PASSWORD
            value: 'grafana'
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: /var/lib/influxdb
