apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    env: learning
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
    env: learning
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
        env: learning
    spec:
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
      containers:
      - name: mysql
        image: my-mysql
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_GROOT_HOST
            value: '172.%'
          - name: MYSQL_GROOT_PASSWORD
            value: 'icantstopthisfeelingdeepinsideofme'
          - name: MYSQL_DATABASE
            value: 'wordpress'
          - name: MYSQL_USER
            value: 'wordpress'
          - name: MYSQL_PASSWORD
            value: 'wordpress'
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
