apiVersion: v1
kind: Secret  
metadata:  
  name: influxdb-secrets
type: Opaque  
stringData:  
  INFLUXDB_ADMIN_USER: groot  
  INFLUXDB_ADMIN_PASSWORD: icantstopthisfeelingdeepinsideofme  
  INFLUXDB_DB: ft_services
  INFLUXDB_USER: grafana  
  INFLUXDB_USER_PASSWORD: grafana
---
apiVersion: v1
kind: Secret  
metadata:  
  name: mysql-secrets
type: Opaque  
stringData:  
  MYSQL_GROOT_PASSWORD: icantstopthisfeelingdeepinsideofme  
  MYSQL_DATABASE: wordpress  
  MYSQL_USER: wordpress
  MYSQL_PASSWORD: wordpress
---
apiVersion: v1
kind: Secret  
metadata:
  name: ftps-secrets
type: Opaque  
stringData:  
  USER: ftps  
  PASSWORD: ftps
