apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf
  namespace: default
  labels:
    k8s-app: telegraf
data:
  telegraf.conf: |+
    [global_tags]
      project = "ft_services"
    [agent]
      hostname = "${HOSTNAME}"
    #################### OUTPUT ###########################
    [[outputs.influxdb]]
      urls = ["${MONITOR_HOST}"]
      database = "${MONITOR_DATABASE}" 
      username = "${MONITOR_USERNAME}"
      password = "${MONITOR_PASSWORD}"
      timeout = "5s"
      
    ##################### INPUT ###########################
    [[inputs.cpu]]
      percpu = false
      totalcpu = true
      collect_cpu_time = false
      report_active = false
    [[inputs.disk]]
      ignore_fs = ["tmpfs", "devtmpfs", "devfs"]
    [[inputs.diskio]]
    [[inputs.kernel]]
    [[inputs.mem]]
    [[inputs.processes]]
    # [[inputs.swap]]
    # [[inputs.system]]
    # [[inputs.kubernetes]]
    #   url = "http://1.1.1.1:10255"

    # Read Nginx's basic status information (ngx_http_stub_status_module)
    [[inputs.nginx]]
    ## An array of Nginx stub_status URI to gather stats.
    urls = ["http://nginx:443/server_status"]

    ## Optional TLS Config
    # tls_ca = "/etc/telegraf/ca.pem"
    # tls_cert = "/etc/telegraf/cert.pem"
    # tls_key = "/etc/telegraf/key.pem"
    ## Use TLS but skip chain & host verification
    # insecure_skip_verify = false

    ## HTTP response timeout (default: 5s)
    response_timeout = "5s"

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telegraf
  namespace: default
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      name: telegraf
  template:
    metadata:
      labels:
        name: telegraf
    spec:
      terminationGracePeriodSeconds: 30
      volumes:
      - name: sys
        hostPath:
          path: /sys
      - name: proc
        hostPath:
          path: /proc
      - name: utmp
        hostPath:
          path: /var/run/utmp
      - name: config
        configMap:
          name: telegraf
      containers:
      - name: telegraf
        image: my-telegraf
        imagePullPolicy: Never
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: "HOST_PROC"
          value: "/rootfs/proc"
        - name: "HOST_SYS"
          value: "/rootfs/sys"
        - name: MONITOR_USERNAME
          value: 'grafana'
        - name: MONITOR_PASSWORD
          value: 'grafana'
        - name: MONITOR_HOST
          value: http://influxdb:8086
        - name: MONITOR_DATABASE
          value: 'ft_services'
        volumeMounts:
        - name: sys
          mountPath: /rootfs/sys
          readOnly: true
        - name: proc
          mountPath: /rootfs/proc
          readOnly: true
        - name: utmp
          mountPath: /var/run/utmp
          readOnly: true
        - name: config
          mountPath: /etc/telegraf
