apiVersion: v1
kind: Service
metadata:
  labels:
    app: test
  name: test
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  selector:
    app: test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: my-nginx
        image: my-nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name : http
        - containerPort: 443
          name : https
