apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
    env: learning
  name: wordpress
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  selector:
    app: wordpress
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress
    env: learning
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
        env: learning
    spec:
      volumes:
        - name: nginx-config
          configMap:
              name: nginx-config
        - name: www-app-wordpress
          configMap:
              name: nginx-config
      shareProcessNamespace: true
      containers:
        - name: my-nginx
          image: my-nginx
          imagePullPolicy: Never
          ports:
          - containerPort: 80
            name : http
          - containerPort: 443
            name : https
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: nginx-config
              readOnly: true
        - name: my-php-fpm
          image: my-php-fpm
          imagePullPolicy: Never
          ports:
          - containerPort: 9000
            name : tcp



---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: wordpress
    env: learning 
data:
  default.conf: |
    # Upstream to abstract backend connection(s) for php
    upstream php {
        server unix:/tmp/php-cgi.socket;
        server 127.0.0.1:9000;
    }

    server {
        listen 80 default_server;   #to listen on 80 in ipv4
        listen [::]:80 default_server;   #to listen on 80 in ipv6
        server_name localhost;
        return 301 https://$host$request_uri; #redirect http -> https
    }

    server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        ssl_certificate      /etc/ssl/certs/nginx-selfsigned.crt;
        ssl_certificate_key  /etc/ssl/private/nginx-selfsigned.key;
        ssl_protocols        SSLv3 TLSv1.3;
        ssl_ciphers          HIGH:!aNULL:!MD5;

        error_page		497	https://$server_name:443$request_uri;   #redirect  when 400 code error

        root /var/www/app;
        index index.php index.html;

        server_name localhost;

        location / {
                  autoindex on;
                  # This is cool because no php is touched for static content.
                  # include the "?$args" part so non-default permalinks doesn't break when using query string
                  # try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
                  # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
                  include fastcgi_params;
                  fastcgi_intercept_errors on;
                  fastcgi_pass php;
                  # The following parameter can be also included in fastcgi_params file
                  fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        # test

    }